import { PrismaClient, IVLevel, StrategyCategory, StrategyType, RiskLevel } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

const strategies = [
  {
    name: 'Long Call',
    category: 'DIRECTIONAL' as const,
    type: 'DEBIT' as const,
    description: 'Buy an OTM call option in a demand zone expecting a bullish move.',
    outlook: ['BULLISH'],
    ivLevels: ['LOW'],
    dteMin: 7,
    dteMax: 14,
    riskLevel: 'AGGRESSIVE' as const,
    legs: [{ type: 'BUY', optionType: 'CE', strikeOffset: 1, lots: 1 }],
    conditions: { iv_levels: ['LOW'], outlook: ['BULLISH'], dte_min: 7, dte_max: 14, zone: 'Demand' },
    rules: { entry: 'Buy OTM call in demand zone', exit: 'Target: Exit at 50% profit', strike_selection: 'At/below DZ distal', delta: '0.3-0.5', vega: 'Positive', theta: 'Negative', max_profit: 'Unlimited', max_loss: 'Premium paid' },
  },
  {
    name: 'Long Put',
    category: 'DIRECTIONAL' as const,
    type: 'DEBIT' as const,
    description: 'Buy an OTM put option in a supply zone expecting a bearish move.',
    outlook: ['BEARISH'],
    ivLevels: ['LOW'],
    dteMin: 7,
    dteMax: 14,
    riskLevel: 'AGGRESSIVE' as const,
    legs: [{ type: 'BUY', optionType: 'PE', strikeOffset: 1, lots: 1 }],
    conditions: { iv_levels: ['LOW'], outlook: ['BEARISH'], dte_min: 7, dte_max: 14, zone: 'Supply' },
    rules: { entry: 'Buy OTM put in supply zone', exit: 'Target: Exit at 50% profit', strike_selection: 'At/below SZ distal', delta: '-0.3 to -0.5', vega: 'Positive', theta: 'Negative', max_profit: 'Unlimited (down to 0)', max_loss: 'Premium paid' },
  },
  {
    name: 'Bull Call Spread',
    category: 'DIRECTIONAL' as const,
    type: 'DEBIT' as const,
    description: 'Buy a lower strike call and sell a higher strike call to profit from a moderate bullish move with reduced cost.',
    outlook: ['BULLISH'],
    ivLevels: ['LOW_NORMAL'],
    dteMin: 10,
    dteMax: 21,
    riskLevel: 'MODERATE' as const,
    legs: [
      { type: 'BUY', optionType: 'CE', strikeOffset: 0, lots: 1 },
      { type: 'SELL', optionType: 'CE', strikeOffset: 2, lots: 1 },
    ],
    conditions: { iv_levels: ['LOW_NORMAL'], outlook: ['BULLISH'], dte_min: 10, dte_max: 21, zone: 'Demand' },
    rules: { entry: 'Buy lower CE, sell higher CE', exit: 'Target or 50% profit', strike_selection: 'Buy DZ distal, Sell SZ distal', delta: '0.2-0.4', vega: 'Near zero', theta: 'Positive', max_profit: 'Spread width − net debit', max_loss: 'Net debit paid' },
  },
  {
    name: 'Bear Put Spread',
    category: 'DIRECTIONAL' as const,
    type: 'DEBIT' as const,
    description: 'Buy a higher strike put and sell a lower strike put to profit from a moderate bearish move.',
    outlook: ['BEARISH'],
    ivLevels: ['LOW_NORMAL'],
    dteMin: 10,
    dteMax: 21,
    riskLevel: 'MODERATE' as const,
    legs: [
      { type: 'BUY', optionType: 'PE', strikeOffset: 0, lots: 1 },
      { type: 'SELL', optionType: 'PE', strikeOffset: 2, lots: 1 },
    ],
    conditions: { iv_levels: ['LOW_NORMAL'], outlook: ['BEARISH'], dte_min: 10, dte_max: 21, zone: 'Supply' },
    rules: { entry: 'Buy higher PE, sell lower PE', exit: 'Target or 50% profit', strike_selection: 'Sell DZ distal, Buy lower', delta: '-0.2 to -0.4', vega: 'Near zero', theta: 'Positive', max_profit: 'Spread width − net debit', max_loss: 'Net debit paid' },
  },
  {
    name: 'Short Put',
    category: 'DIRECTIONAL' as const,
    type: 'CREDIT' as const,
    description: 'Sell an OTM put below a demand zone. Profits when underlying stays above strike via theta decay.',
    outlook: ['BULLISH'],
    ivLevels: ['HIGH'],
    dteMin: 7,
    dteMax: 21,
    riskLevel: 'MODERATE' as const,
    legs: [{ type: 'SELL', optionType: 'PE', strikeOffset: 1, lots: 1 }],
    conditions: { iv_levels: ['HIGH'], outlook: ['BULLISH'], dte_min: 7, dte_max: 21, zone: 'Demand' },
    rules: { entry: 'Sell OTM put below demand zone', exit: 'Target: 50% or Stop Loss', strike_selection: 'Below DZ distal', delta: '-0.1 to -0.25', vega: 'Negative', theta: 'Positive', max_profit: 'Premium received', max_loss: 'Strike − premium (large)' },
  },
  {
    name: 'Short Call',
    category: 'DIRECTIONAL' as const,
    type: 'CREDIT' as const,
    description: 'Sell an OTM call above a supply zone. Profits when underlying stays below strike.',
    outlook: ['BEARISH'],
    ivLevels: ['HIGH'],
    dteMin: 7,
    dteMax: 21,
    riskLevel: 'AGGRESSIVE' as const,
    legs: [{ type: 'SELL', optionType: 'CE', strikeOffset: 1, lots: 1 }],
    conditions: { iv_levels: ['HIGH'], outlook: ['BEARISH'], dte_min: 7, dte_max: 21, zone: 'Supply' },
    rules: { entry: 'Sell OTM call above supply zone', exit: 'Target: 50% or Stop Loss', strike_selection: 'Above SZ distal', delta: '0.1-0.25', vega: 'Negative', theta: 'Positive', max_profit: 'Premium received', max_loss: 'Unlimited' },
  },
  {
    name: 'Bull Put Spread',
    category: 'DIRECTIONAL' as const,
    type: 'CREDIT' as const,
    description: 'Sell a higher strike put and buy a lower strike put for a bullish, defined-risk credit spread.',
    outlook: ['BULLISH'],
    ivLevels: ['HIGH_NORMAL'],
    dteMin: 10,
    dteMax: 21,
    riskLevel: 'MODERATE' as const,
    legs: [
      { type: 'SELL', optionType: 'PE', strikeOffset: 1, lots: 1 },
      { type: 'BUY', optionType: 'PE', strikeOffset: 2, lots: 1 },
    ],
    conditions: { iv_levels: ['HIGH_NORMAL'], outlook: ['BULLISH'], dte_min: 10, dte_max: 21, zone: 'Demand' },
    rules: { entry: 'Sell higher PE, buy lower PE', exit: 'Target: 50% or SL', strike_selection: 'Sell DZ, Buy below', delta: '-0.1 to -0.2', vega: 'Negative', theta: 'Positive', max_profit: 'Net credit', max_loss: 'Spread width − credit' },
  },
  {
    name: 'Bear Call Spread',
    category: 'DIRECTIONAL' as const,
    type: 'CREDIT' as const,
    description: 'Sell a lower strike call and buy a higher strike call for a bearish, defined-risk credit spread.',
    outlook: ['BEARISH'],
    ivLevels: ['HIGH_NORMAL'],
    dteMin: 10,
    dteMax: 21,
    riskLevel: 'MODERATE' as const,
    legs: [
      { type: 'SELL', optionType: 'CE', strikeOffset: 1, lots: 1 },
      { type: 'BUY', optionType: 'CE', strikeOffset: 2, lots: 1 },
    ],
    conditions: { iv_levels: ['HIGH_NORMAL'], outlook: ['BEARISH'], dte_min: 10, dte_max: 21, zone: 'Supply' },
    rules: { entry: 'Sell lower CE, buy higher CE', exit: 'Target: 50% or SL', strike_selection: 'Sell SZ, Buy above', delta: '0.1-0.2', vega: 'Negative', theta: 'Positive', max_profit: 'Net credit', max_loss: 'Spread width − credit' },
  },
  {
    name: 'Put Calendar Spread',
    category: 'NON_DIRECTIONAL' as const,
    type: 'DEBIT' as const,
    description: 'Sell a near-term put and buy a far-term put at the same strike. Profits from differential time decay.',
    outlook: ['NEUTRAL'],
    ivLevels: ['NORMAL'],
    dteMin: 10,
    dteMax: 21,
    riskLevel: 'MODERATE' as const,
    legs: [
      { type: 'SELL', optionType: 'PE', strikeOffset: 0, lots: 1, expiry: 'near' },
      { type: 'BUY', optionType: 'PE', strikeOffset: 0, lots: 1, expiry: 'far' },
    ],
    conditions: { iv_levels: ['NORMAL'], outlook: ['NEUTRAL'], dte_min: 10, dte_max: 21, zone: 'Any' },
    rules: { entry: 'Sell near-expiry PE, buy far-expiry PE at same strike', exit: '50% or range break', strike_selection: 'Same strike, different expiry', delta: '~0 (neutral)', vega: 'Positive', theta: 'Positive', max_profit: 'Extrinsic value difference at near expiry', max_loss: 'Net debit paid' },
  },
  {
    name: 'Call Calendar Spread',
    category: 'NON_DIRECTIONAL' as const,
    type: 'DEBIT' as const,
    description: 'Sell a near-term call and buy a far-term call at the same strike. Profits from differential time decay.',
    outlook: ['NEUTRAL'],
    ivLevels: ['NORMAL'],
    dteMin: 10,
    dteMax: 21,
    riskLevel: 'MODERATE' as const,
    legs: [
      { type: 'SELL', optionType: 'CE', strikeOffset: 0, lots: 1, expiry: 'near' },
      { type: 'BUY', optionType: 'CE', strikeOffset: 0, lots: 1, expiry: 'far' },
    ],
    conditions: { iv_levels: ['NORMAL'], outlook: ['NEUTRAL'], dte_min: 10, dte_max: 21, zone: 'Any' },
    rules: { entry: 'Sell near-expiry CE, buy far-expiry CE at same strike', exit: '50% or range break', strike_selection: 'Same strike, different expiry', delta: '~0 (neutral)', vega: 'Positive', theta: 'Positive', max_profit: 'Extrinsic value difference at near expiry', max_loss: 'Net debit paid' },
  },
  {
    name: 'Short Strangle',
    category: 'NON_DIRECTIONAL' as const,
    type: 'CREDIT' as const,
    description: 'Sell an OTM call and an OTM put. Profits when underlying stays within a defined range via premium decay.',
    outlook: ['NEUTRAL'],
    ivLevels: ['HIGH'],
    dteMin: 7,
    dteMax: 21,
    riskLevel: 'AGGRESSIVE' as const,
    legs: [
      { type: 'SELL', optionType: 'CE', strikeOffset: 1, lots: 1 },
      { type: 'SELL', optionType: 'PE', strikeOffset: 1, lots: 1 },
    ],
    conditions: { iv_levels: ['HIGH'], outlook: ['NEUTRAL'], dte_min: 7, dte_max: 21, zone: 'S&D' },
    rules: { entry: 'Sell OTM CE above SZ, sell OTM PE below DZ', exit: '50% or SL hits', strike_selection: 'Call above SZ, Put below DZ', delta: '~0 (net)', vega: 'Negative', theta: 'Positive', max_profit: 'Total premium received', max_loss: 'Unlimited on both sides' },
  },
  {
    name: 'Long Strangle',
    category: 'NON_DIRECTIONAL' as const,
    type: 'DEBIT' as const,
    description: 'Buy an OTM call and an OTM put. Profits from a large move in either direction (event plays).',
    outlook: ['NEUTRAL'],
    ivLevels: ['LOW'],
    dteMin: 7,
    dteMax: 14,
    riskLevel: 'AGGRESSIVE' as const,
    legs: [
      { type: 'BUY', optionType: 'CE', strikeOffset: 1, lots: 1 },
      { type: 'BUY', optionType: 'PE', strikeOffset: 1, lots: 1 },
    ],
    conditions: { iv_levels: ['LOW'], outlook: ['NEUTRAL'], dte_min: 7, dte_max: 14, zone: 'S&D' },
    rules: { entry: 'Buy OTM CE and OTM PE around current price', exit: 'On event move or SL', strike_selection: 'Call above, Put below', delta: '~0 (net)', vega: 'Positive', theta: 'Negative', max_profit: 'Unlimited both sides', max_loss: 'Total premium paid' },
  },
  {
    name: 'Short Iron Condor',
    category: 'NON_DIRECTIONAL' as const,
    type: 'CREDIT' as const,
    description: '4-leg range strategy: sell OTM strangle and buy wider wings for protection. Best in high-IV rangebound markets.',
    outlook: ['NEUTRAL'],
    ivLevels: ['HIGH_NORMAL', 'HIGH'],
    dteMin: 10,
    dteMax: 21,
    riskLevel: 'MODERATE' as const,
    legs: [
      { type: 'SELL', optionType: 'CE', strikeOffset: 1, lots: 1 },
      { type: 'BUY', optionType: 'CE', strikeOffset: 2, lots: 1 },
      { type: 'SELL', optionType: 'PE', strikeOffset: 1, lots: 1 },
      { type: 'BUY', optionType: 'PE', strikeOffset: 2, lots: 1 },
    ],
    conditions: { iv_levels: ['HIGH_NORMAL', 'HIGH'], outlook: ['NEUTRAL'], dte_min: 10, dte_max: 21, zone: 'S&D' },
    rules: { entry: 'Sell OTM CE + PE, buy further OTM wings', exit: '50% or range break', strike_selection: 'Sell far above SZ & below DZ', delta: '<0.25 each leg', vega: 'Negative', theta: 'Positive', max_profit: 'Net credit received', max_loss: 'Spread width − credit' },
  },
  {
    name: 'Long Iron Condor',
    category: 'NON_DIRECTIONAL' as const,
    type: 'DEBIT' as const,
    description: '4-leg strategy: buy closer OTM options and sell further OTM caps. Profits from breakout in low-IV environment.',
    outlook: ['NEUTRAL'],
    ivLevels: ['LOW', 'LOW_NORMAL'],
    dteMin: 10,
    dteMax: 21,
    riskLevel: 'CONSERVATIVE' as const,
    legs: [
      { type: 'BUY', optionType: 'CE', strikeOffset: 1, lots: 1 },
      { type: 'SELL', optionType: 'CE', strikeOffset: 2, lots: 1 },
      { type: 'BUY', optionType: 'PE', strikeOffset: 1, lots: 1 },
      { type: 'SELL', optionType: 'PE', strikeOffset: 2, lots: 1 },
    ],
    conditions: { iv_levels: ['LOW', 'LOW_NORMAL'], outlook: ['NEUTRAL'], dte_min: 10, dte_max: 21, zone: 'S&D' },
    rules: { entry: 'Buy OTM CE + PE, sell further OTM caps', exit: '50% or on breakout', strike_selection: 'Buy anchors, sell offset', delta: '<0.25 each leg', vega: 'Positive', theta: 'Negative', max_profit: 'Spread width − net debit', max_loss: 'Net debit paid' },
  },
  {
    name: 'Short Iron Butterfly',
    category: 'NON_DIRECTIONAL' as const,
    type: 'CREDIT' as const,
    description: 'Sell ATM straddle and buy OTM wings. Maximum profit when underlying expires exactly at ATM strike.',
    outlook: ['NEUTRAL'],
    ivLevels: ['HIGH_NORMAL', 'HIGH'],
    dteMin: 10,
    dteMax: 21,
    riskLevel: 'MODERATE' as const,
    legs: [
      { type: 'SELL', optionType: 'CE', strikeOffset: 0, lots: 1 },
      { type: 'BUY', optionType: 'CE', strikeOffset: 1, lots: 1 },
      { type: 'SELL', optionType: 'PE', strikeOffset: 0, lots: 1 },
      { type: 'BUY', optionType: 'PE', strikeOffset: 1, lots: 1 },
    ],
    conditions: { iv_levels: ['HIGH_NORMAL', 'HIGH'], outlook: ['NEUTRAL'], dte_min: 10, dte_max: 21, zone: 'ATM' },
    rules: { entry: 'Sell ATM CE + PE, buy equidistant OTM wings', exit: '50% profit target', strike_selection: 'Sell at ATM, wings at ±1 strike', delta: '~0 (ATM)', vega: 'Negative', theta: 'Positive', max_profit: 'Net credit received', max_loss: 'Spread width − credit' },
  },
  {
    name: 'Long Iron Butterfly',
    category: 'NON_DIRECTIONAL' as const,
    type: 'DEBIT' as const,
    description: 'Buy ATM straddle and sell OTM wings. Profits when underlying makes a large move from ATM in low-IV conditions.',
    outlook: ['NEUTRAL'],
    ivLevels: ['LOW', 'LOW_NORMAL'],
    dteMin: 10,
    dteMax: 21,
    riskLevel: 'CONSERVATIVE' as const,
    legs: [
      { type: 'BUY', optionType: 'CE', strikeOffset: 0, lots: 1 },
      { type: 'SELL', optionType: 'CE', strikeOffset: 1, lots: 1 },
      { type: 'BUY', optionType: 'PE', strikeOffset: 0, lots: 1 },
      { type: 'SELL', optionType: 'PE', strikeOffset: 1, lots: 1 },
    ],
    conditions: { iv_levels: ['LOW', 'LOW_NORMAL'], outlook: ['NEUTRAL'], dte_min: 10, dte_max: 21, zone: 'ATM' },
    rules: { entry: 'Buy ATM CE + PE, sell equidistant OTM caps', exit: '50% profit target', strike_selection: 'Buy at ATM, sell offset OTM', delta: '~0 (ATM)', vega: 'Positive', theta: 'Negative', max_profit: 'Spread width − net debit', max_loss: 'Net debit paid' },
  },
  {
    name: 'Long Synthetic',
    category: 'DIRECTIONAL' as const,
    type: 'DEBIT' as const,
    description: 'Buy a call and sell a put at the same strike. Replicates a long futures position using options.',
    outlook: ['BULLISH'],
    ivLevels: ['NORMAL'],
    dteMin: null,
    dteMax: null,
    riskLevel: 'AGGRESSIVE' as const,
    legs: [
      { type: 'BUY', optionType: 'CE', strikeOffset: 0, lots: 1 },
      { type: 'SELL', optionType: 'PE', strikeOffset: 0, lots: 1 },
    ],
    conditions: { iv_levels: ['NORMAL'], outlook: ['BULLISH'], dte_min: null, dte_max: null, zone: 'Any' },
    rules: { entry: 'Buy ATM CE, sell ATM PE at same strike', exit: 'Target price or SL', strike_selection: 'Same strike both legs', delta: '+1.0 (stock-like)', vega: 'Near zero', theta: 'Near zero', max_profit: 'Unlimited', max_loss: 'Unlimited (downside)' },
  },
  {
    name: 'Short Synthetic',
    category: 'DIRECTIONAL' as const,
    type: 'CREDIT' as const,
    description: 'Sell a call and buy a put at the same strike. Replicates a short futures position using options.',
    outlook: ['BEARISH'],
    ivLevels: ['NORMAL'],
    dteMin: null,
    dteMax: null,
    riskLevel: 'AGGRESSIVE' as const,
    legs: [
      { type: 'SELL', optionType: 'CE', strikeOffset: 0, lots: 1 },
      { type: 'BUY', optionType: 'PE', strikeOffset: 0, lots: 1 },
    ],
    conditions: { iv_levels: ['NORMAL'], outlook: ['BEARISH'], dte_min: null, dte_max: null, zone: 'Any' },
    rules: { entry: 'Sell ATM CE, buy ATM PE at same strike', exit: 'Target price or SL', strike_selection: 'Same strike both legs', delta: '-1.0 (stock-like)', vega: 'Near zero', theta: 'Near zero', max_profit: 'Unlimited (downside)', max_loss: 'Unlimited (upside)' },
  },
  {
    name: 'Put Ratio Back Spread',
    category: 'VOLATILITY' as const,
    type: 'CREDIT' as const,
    description: 'Sell 1 higher-strike put and buy 2 lower-strike puts. Advanced strategy for large downside moves in high IV.',
    outlook: ['BULLISH'],
    ivLevels: ['HIGH'],
    dteMin: 10,
    dteMax: 21,
    riskLevel: 'AGGRESSIVE' as const,
    legs: [
      { type: 'SELL', optionType: 'PE', strikeOffset: 1, lots: 1 },
      { type: 'BUY', optionType: 'PE', strikeOffset: 2, lots: 2 },
    ],
    conditions: { iv_levels: ['HIGH'], outlook: ['BULLISH'], dte_min: 10, dte_max: 21, zone: 'Support' },
    rules: { entry: 'Sell 1 higher PE, buy 2 lower PEs', exit: '50% or SL (advanced)', strike_selection: 'Sell above support, buy at/below support', delta: 'Varies (complex)', vega: 'Complex', theta: 'Positive', max_profit: 'Unlimited on strong downside', max_loss: 'Between strikes (limited zone)' },
  },
  {
    name: 'Call Ratio Front Spread',
    category: 'VOLATILITY' as const,
    type: 'CREDIT' as const,
    description: 'Buy 1 lower-strike call and sell 2 higher-strike calls. Profits from mild bearish or sideways move in high IV.',
    outlook: ['BEARISH'],
    ivLevels: ['HIGH'],
    dteMin: 10,
    dteMax: 21,
    riskLevel: 'AGGRESSIVE' as const,
    legs: [
      { type: 'BUY', optionType: 'CE', strikeOffset: 0, lots: 1 },
      { type: 'SELL', optionType: 'CE', strikeOffset: 1, lots: 2 },
    ],
    conditions: { iv_levels: ['HIGH'], outlook: ['BEARISH'], dte_min: 10, dte_max: 21, zone: 'Resistance' },
    rules: { entry: 'Buy 1 lower CE, sell 2 higher CEs', exit: '50% or SL (advanced)', strike_selection: 'Buy at resistance, sell above', delta: 'Varies (complex)', vega: 'Complex', theta: 'Positive', max_profit: 'Between strikes (moderate move)', max_loss: 'Unlimited on strong upside' },
  },
  {
    name: 'Breakout for Free',
    category: 'VOLATILITY' as const,
    type: 'CREDIT' as const,
    description: 'Sell 2 puts and buy 1 call funded by put premium. Get a bullish breakout play at near-zero or net credit.',
    outlook: ['BULLISH'],
    ivLevels: ['NORMAL', 'HIGH_NORMAL', 'HIGH'],
    dteMin: 10,
    dteMax: 21,
    riskLevel: 'AGGRESSIVE' as const,
    legs: [
      { type: 'SELL', optionType: 'PE', strikeOffset: 1, lots: 2 },
      { type: 'BUY', optionType: 'CE', strikeOffset: 1, lots: 1 },
    ],
    conditions: { iv_levels: ['NORMAL', 'HIGH_NORMAL', 'HIGH'], outlook: ['BULLISH'], dte_min: 10, dte_max: 21, zone: 'Breakout' },
    rules: { entry: 'Sell 2 OTM PEs below DZ, buy 1 OTM CE above SZ', exit: 'Breakout or range holds', strike_selection: 'Puts at DZ, Call at SZ', delta: 'Positive net', vega: 'Varies', theta: 'Positive', max_profit: 'Unlimited on breakout', max_loss: 'Large if underlying falls sharply' },
  },
  {
    name: 'Call Ratio Spread',
    category: 'DIRECTIONAL' as const,
    type: 'VARIES' as const,
    description: 'Buy 1 lower call and sell 2 higher calls. Best for moderate bullish moves; profits in a sweet spot.',
    outlook: ['BULLISH'],
    ivLevels: ['LOW_NORMAL', 'NORMAL'],
    dteMin: 10,
    dteMax: 21,
    riskLevel: 'AGGRESSIVE' as const,
    legs: [
      { type: 'BUY', optionType: 'CE', strikeOffset: 0, lots: 1 },
      { type: 'SELL', optionType: 'CE', strikeOffset: 1, lots: 2 },
    ],
    conditions: { iv_levels: ['LOW_NORMAL', 'NORMAL'], outlook: ['BULLISH'], dte_min: 10, dte_max: 21, zone: 'Uptrend' },
    rules: { entry: 'Buy 1 lower CE, sell 2 higher CEs', exit: '50% or SL (advanced)', strike_selection: 'Buy lower, sell higher', delta: 'Varies', vega: 'Varies', theta: 'Positive', max_profit: 'Between strikes (moderate move)', max_loss: 'Unlimited on strong upside' },
  },
  {
    name: 'Double Diagonal',
    category: 'NON_DIRECTIONAL' as const,
    type: 'CREDIT' as const,
    description: '4-leg strategy combining two diagonal spreads at different strikes. Stable range-bound income play in low IV.',
    outlook: ['NEUTRAL'],
    ivLevels: ['LOW'],
    dteMin: 10,
    dteMax: 21,
    riskLevel: 'CONSERVATIVE' as const,
    legs: [
      { type: 'SELL', optionType: 'CE', strikeOffset: 1, lots: 1, expiry: 'near' },
      { type: 'SELL', optionType: 'PE', strikeOffset: 1, lots: 1, expiry: 'near' },
      { type: 'BUY', optionType: 'CE', strikeOffset: 2, lots: 1, expiry: 'far' },
      { type: 'BUY', optionType: 'PE', strikeOffset: 2, lots: 1, expiry: 'far' },
    ],
    conditions: { iv_levels: ['LOW'], outlook: ['NEUTRAL'], dte_min: 10, dte_max: 21, zone: 'Range' },
    rules: { entry: 'Sell near-expiry OTM CE + PE, buy far-expiry further OTM CE + PE', exit: '50% or range break', strike_selection: 'Sell near diff strike, buy far', delta: '<0.25 each', vega: 'Balanced', theta: 'Positive', max_profit: 'Net credit + time decay differential', max_loss: 'Net debit if held to near expiry' },
  },
]

async function main() {
  const hash = await bcrypt.hash('Admin@1234', 12)
  const admin = await prisma.user.upsert({
    where: { email: 'admin@optraassistant.com' },
    update: {},
    create: {
      name: 'Admin',
      email: 'admin@optraassistant.com',
      passwordHash: hash,
      emailVerified: true,
      status: 'ACTIVE',
      role: 'ADMIN',
    },
  })
  console.log('Seeded admin:', admin.email)

  for (const s of strategies) {
    const data = {
      ...s,
      ivLevels: s.ivLevels as IVLevel[],
      category: s.category as StrategyCategory,
      type: s.type as StrategyType,
      riskLevel: s.riskLevel as RiskLevel,
    }
    await prisma.strategy.upsert({
      where: { name: s.name },
      create: data,
      update: data,
    })
  }
  console.log(`Seeded ${strategies.length} strategies.`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
